// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBRcyP8FLsIIe0Vjdjhp_75QqXCXdPIkL4",
      authDomain: "maize-plant-e19d0.firebaseapp.com",
      databaseURL: 'https://maize-plant-e19d0-default-rtdb.firebaseio.com/',
      projectId: "maize-plant-e19d0",
      storageBucket: "maize-plant-e19d0.firebasestorage.app",
      messagingSenderId: "255677700824",
      appId: "1:255677700824:web:38a0cefb169551a0e515ad",
      measurementId: "G-HYD7CWPCRJ"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk-69vNXS2-PWsuY4BrTBJu3ECZDbd2OQ',
    appId: '1:255677700824:android:634b2bfc63a36abde515ad',
    messagingSenderId: '255677700824',
    projectId: 'maize-plant-e19d0',
    databaseURL: 'https://maize-plant-e19d0-default-rtdb.firebaseio.com/',
    storageBucket: "maize-plant-e19d0.firebasestorage.app",
  );
}
